name: Run combined tests for fine, geokit, glaes and reskit
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual run' 
#   push:
#     branches: 
#       - main

    
  
jobs:
    TestCombinedInstalaltions:
        name: Test on ${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                # os: ["ubuntu-latest","ubuntu-20.04", "macos-latest","macos-13","macos-12", "macos-11","windows-latest","windows-2019"]
                os: ["ubuntu-latest"]
        steps:
            - uses: conda-incubator/setup-miniconda@v3
              with:
                miniforge-version: latest
                channels: conda-forge
                activate-environment: test_env
            - name: Install libraries
              shell: pwsh
              id: install-step
              run: |
                    ls
                    echo "LS Done"
                    mamba install -v -n test_env fine geokit glaes reskit pytest=6.2.4 scikit-learn=1.1.3
                    echo "Installation done"
                    conda list -n test_env
                    echo "libaries printed"                          
            - name: Get fine version
              shell: pwsh
              id: fine-version
              run: |
                $FINE_STRING = conda list -e -n test_env fine | Out-String
                echo the fine string is $FINE_STRING
                $FINE_VERSION = [regex]::Match($FINE_STRING, 'fine=(\d+\.\d+\.\d+)=').Groups[1].Value 
                echo "FINE_VERSION_NUMBER=$FINE_VERSION" >> $GITHUB_OUTPUT
                echo $FINE_VERSION_NUMBER
                echo "FINE_VERSION_NUMBER_WITH_V=v$FINE_VERSION" >> $GITHUB_OUTPUT
                echo $FINE_VERSION_NUMBER_WITH_V
            - name: Get fine version
              shell: pwsh
              id: other-version
              run: |
                  $GEOKIT_STRING = conda list -e -n test_env geokit | Out-String
                  echo The geokit string is $GEOKIT_STRING
                  $GEOKIT_VERSION = [regex]::Match($GEOKIT_STRING, 'geokit=(\d+\.\d+\.\d+)=').Groups[1].Value 
                  echo "GEOKIT_VERSION=$GEOKIT_VERSION" >> $GITHUB_OUTPUT
                  echo Geokit version: $GEOKIT_VERSION

                  $GLAES_STRING = conda list -e -n test_env geokit | Out-String
                  echo The glaes string is $GLAES_STRING
                  $GLAES_VERSION = [regex]::Match($GLAES_STRING, 'glaes=(\d+\.\d+\.\d+)=').Groups[1].Value 
                  echo "GLAES_VERSION=$GLAES_VERSION" >> $GITHUB_OUTPUT
                  echo Glaes Version: $GLAES_VERSION 
                  
                  $RESKIT_STRING = conda list -e -n test_env reskit | Out-String
                  echo The reskit string is $RESKIT_STRING
                  $RESKIT_VERSION = [regex]::Match($RESKIT_STRING, 'glaes=(\d+\.\d+\.\d+)=').Groups[1].Value 
                  echo "RESKIT_VERSION=$RESKIT_VERSION" >> $GITHUB_OUTPUT
                  The reskit version is $RESKIT_VERSION
            - name: Checkout Fine
              uses: actions/checkout@v4
              with:
                repository: FZJ-IEK3-VSA/FINE
                path: './fine' 
                ref: ${{ steps.fine-version.outputs.FINE_VERSION_NUMBER_WITH_V }}
                fetch-depth: 0 
            - name: Checkout geokit
              uses: actions/checkout@v4
              with:
                repository: FZJ-IEK3-VSA/geokit
                path: './geokit'
                ref: ${{ steps.other-version.outputs.GEOKIT_VERSION }}
                fetch-depth: 0 
            - name: Checkout glaes
              uses: actions/checkout@v4
              with:
                repository: FZJ-IEK3-VSA/glaes
                path: './glaes'
                ref: ${{ steps.other-version.outputs.GLAES_VERSION }}
                fetch-depth: 0 
            - name: Checkout Reskit
              uses: actions/checkout@v4
              with:
                repository: FZJ-IEK3-VSA/RESKit
                path: './reskit' 
                ref: ${{ steps.other-version.outputs.RESKIT_VERSION }}
                fetch-depth: 0      
            
            - name: Run pytest for fine
              shell: pwsh
              run: |
                    echo "Start ls"
                    ls
                    echo "ls terminated"
                    cd fine
                    echo "start pytest"
                    conda run -n test_env python -m pytest test/
                    echo "Pytest done"
            - name: Run pytest for geokit
              shell: pwsh
              run: |
                    echo "Start ls"
                    ls
                    echo "ls terminated"
                    cd geokit
                    echo "start pytest"
                    conda run -n test_env python -m pytest
                    echo "Pytest done"

            - name: Run pytest for glaes
              shell: pwsh
              run: |
                    echo "Start ls"
                    ls
                    echo "ls terminated"
                    cd glaes
                    echo "start pytest"
                    conda run -n test_env python -m pytest
                    echo "Pytest done"
            - name: Run pytest for reskit
              shell: pwsh
              run: |
                    echo "Start ls"
                    ls
                    echo "ls terminated"
                    cd reskit
                    echo "start pytest"
                    conda run -n test_env python -m pytest
                    echo "Pytest done"

                    
